# Generated by Django 4.1.7 on 2023-04-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallAnalitics',
        ),
    ]
