# Generated by Django 4.1.7 on 2023-04-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_callanalitics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
