# Generated by Django 4.1.7 on 2023-04-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('number_calls', models.IntegerField()),
                ('retry_count', models.IntegerField()),
                ('repeated_time', models.IntegerField()),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='myapp.data')),
            ],
        ),
    ]
