# Generated by Django 4.1.7 on 2023-04-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phones', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=255)),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_analytics', to='myapp.data')),
            ],
        ),
    ]
