# Generated by Django 4.1.7 on 2023-04-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_callanalytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='data_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='data_id',
        ),
        migrations.DeleteModel(
            name='CallAnalytics',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
