# Generated by Django 4.1.7 on 2023-04-14 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0011_remove_contacts_data_id_remove_schedule_data_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('number_calls', models.IntegerField()),
                ('retry_count', models.IntegerField()),
                ('repeated_time', models.IntegerField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='myapp.data')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phones', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='myapp.data')),
            ],
        ),
        migrations.CreateModel(
            name='CallAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phones', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=255)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_analytics', to='myapp.data')),
            ],
        ),
    ]
