# Generated by Django 4.1.7 on 2023-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='verification_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
